### ISSUE TITLE
Does not support numeric suffixes?

### ISSUE THREAD

**Issue by ddxl123** [fkleon/math-expressions#71] opened 2022-10-17 17:19 UTC
```
final ContextModel cm = ContextModel();
cm.bindVariable(Variable('name1'), Number(123));
print(Parser().parse(c.textEditingController.text).evaluate(EvaluationType.REAL, cm));
```
error:
```
E/flutter (28656): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: The input String is not a correct expression
E/flutter (28656): #0      Parser.parse (package:math_expressions/src/parser.dart:142:7)
E/flutter (28656): #1      TestHome.build.<anonymous closure>.<anonymous closure> (package:aaa/home/test/TestHome.dart:62:50)
E/flutter (28656): #2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
E/flutter (28656): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
E/flutter (28656): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
E/flutter (28656): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
E/flutter (28656): #6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
E/flutter (28656): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
E/flutter (28656): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
E/flutter (28656): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
E/flutter (28656): #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
E/flutter (28656): #11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
E/flutter (28656): #12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
E/flutter (28656): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
E/flutter (28656): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (28656): #15     _invoke1 (dart:ui/hooks.dart:167:13)
E/flutter (28656): #16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
E/flutter (28656): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter (28656): 

```

**Comment by fkleon** [comment] 2022-10-26 23:29
H, thanks for reporting this issue. I believe this is a duplicate of #35

**Comment by fkleon** [comment] 2022-10-26 23:30
I've updated the title of other issue to be a bit more descriptive, closing this one as duplicate

**Closed by fkleon** 2022-10-26 23:30 UTC
Labels: bug, duplicate
