### ISSUE TITLE
Module does not work with numerical values.

### ISSUE THREAD

**Issue by AshishisLiquid** [fkleon/math-expressions#50] opened 2021-04-01 12:24 UTC
According to modules rule and other calculator. Provided number should be divided by 100 to get the result.

As a example :

`12% = 0.12`.

But when i try to use modules on the numerical value

Code i tried : 

```
Expression exp = p.parse('12%');
print(exp.evaluate(EvaluationType.REAL, null).toString());
```

> RangeError (index): Invalid value: Valid value range is empty: -1

**Comment by fkleon** [comment] 2021-04-01 18:33
Thanks for the report. I think this is a duplicate of #28.

Percentage notation is not supported by the parser. Please use decimal notation instead.

**Closed** 2021-04-01 18:33 UTC
Labels: duplicate
